export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const REQUEST_FORECAST = 'REQUEST_FORECAST';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_FORECAST = 'FETCH_FORECAST';
export const SELECT_CITY = 'SELECT_CITY';
